### PR TITLE
v0.4.0: Simplification

### PR DESCRIPTION
**Pull request by dillonredding**
## Fun Changes

- Replacing custom transformation and validation logic with `class-transformer` and `class-validator` packages
- Simplifying API so that all parsing is done via static factory method instead of constructor

## Boring Changes

- Updating build pipeline to use newer Node versions
- Removing tests from the build script
- Separating Prettier and Jest config from `package.json`
- Narrowing tests to only Node
- Moving tests closer to files

### CODE REVIEW

**Comment by SeeSharpCode** [comment]
Mostly skimmed due to the amount of changes, but I'm onboard with the types of changes.

What is "Narrowing tests to only Node" referring to?

**Comment by dillonredding** [comment]
> What is "Narrowing tests to only Node" referring to?

The `test*` script changes in `package.json` to remove running the tests through the `jsdom` environment.

**Comment by dillonredding** [comment]
Need to figure out how these changes impact downstream dependencies. Planning on publishing an alpha version to NPM.

**Comment by dillonredding** [comment]
@SeeSharpCode I updated the README and CHANGELOG, which might give a better overview of the changes. In any case, this is ready for review.

**Review by SeeSharpCode — APPROVED** [review]

**Pull request merged**
